import { join } from "node:path";
import type { SelfHostedBackend } from "../config.ts";
import {
  envAt,
  envStore,
  ok,
  putEnv,
  writeFile,
} from "../setup-context.ts";

export type BunSqliteOptions = {
  publicUrl: string;
  port: number;
  dbPath: string;
};

export function bunSqlite(options: BunSqliteOptions): SelfHostedBackend {
  return {
    kind: "bun-sqlite",
    ...options,
    plan() {
      return [
        "write `.env` (db path, port, BETTER_AUTH_SECRET)",
        "verify `.env` has those values",
      ];
    },
    async setup(ctx) {
      const path = join(ctx.cwd, ".env");
      const existing = envAt(path);
      ctx.store = envStore(path);
      if (!existing.BETTER_AUTH_SECRET && !existing.OPENCMS_DB) {
        writeFile(path, renderEnv(this, ctx.generateSecret()));
        ok(ctx, "Wrote .env with a generated BETTER_AUTH_SECRET");
        return;
      }
      putEnv(path, {
        OPENCMS_DB: this.dbPath,
        OPENCMS_PORT: String(this.port),
        BETTER_AUTH_SECRET: existing.BETTER_AUTH_SECRET ? undefined : ctx.generateSecret(),
        BETTER_AUTH_URL: /^https?:\/\/(localhost|127\.0\.0\.1)([:/]|$)/.test(this.publicUrl)
          ? undefined
          : this.publicUrl,
      });
      ok(ctx, "Updated .env (existing secrets kept)");
    },
    async test(ctx) {
      const path = join(ctx.cwd, ".env");
      const env = envAt(path);
      ctx.store = ctx.store ?? envStore(path);
      if (!env.BETTER_AUTH_SECRET) throw new Error(".env is missing BETTER_AUTH_SECRET");
      if (env.OPENCMS_DB !== this.dbPath) {
        throw new Error(`.env OPENCMS_DB is ${env.OPENCMS_DB ?? "unset"}, expected ${this.dbPath}`);
      }
      if (env.OPENCMS_PORT !== String(this.port)) {
        throw new Error(`.env OPENCMS_PORT is ${env.OPENCMS_PORT ?? "unset"}, expected ${this.port}`);
      }
      ok(ctx, ".env looks good");
    },
    nextSteps() {
      return "bun run build:admin && bun run dev";
    },
  };
}

function renderEnv(backend: SelfHostedBackend, secret: string): string {
  const isLocal = /^https?:\/\/(localhost|127\.0\.0\.1)([:/]|$)/.test(backend.publicUrl);
  const lines = [
    "# Generated by `opencms setup`. Runtime config for the Bun + SQLite profile.",
    "# Bun loads this automatically for `bun run dev`. Never commit this file.",
    `OPENCMS_DB=${backend.dbPath}`,
    `OPENCMS_PORT=${backend.port}`,
    `BETTER_AUTH_SECRET=${secret}`,
  ];
  if (!isLocal) lines.push(`BETTER_AUTH_URL=${backend.publicUrl}`);
  return lines.join("\n") + "\n";
}
