import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import type { CloudflareBackend } from "../config.ts";
import {
  envAt,
  note,
  ok,
  progress,
  putEnv,
  workerDir,
  wranglerStore,
  writeFile,
  type SetupContext,
} from "../setup-context.ts";
import {
  isPlaceholderDatabaseId,
  readDatabaseId,
  setDatabaseId,
  setDatabaseName,
  setWorkerName,
  upsertCustomDomain,
  upsertVars,
} from "../toml.ts";
import { isLoggedIn, parseD1List, parseDatabaseId, wranglerInvocation } from "../wrangler.ts";

export type CloudflareOptions = {
  workerName: string;
  d1Name: string;
  customDomain?: string;
};

export function cloudflare(options: CloudflareOptions): CloudflareBackend {
  return {
    kind: "cloudflare",
    ...options,
    plan() {
      const steps = [
        "log in to Cloudflare if needed",
        `create D1 database "${this.d1Name}"`,
        "write database_id into apps/worker/wrangler.toml",
        "put BETTER_AUTH_SECRET (wrangler secret + .dev.vars)",
        `verify D1 "${this.d1Name}" with SELECT 1`,
      ];
      if (this.customDomain) steps.push(`attach custom domain ${this.customDomain}`);
      return steps;
    },
    async setup(ctx) {
      await setupCloudflare(this, ctx);
    },
    async test(ctx) {
      await testCloudflare(this, ctx);
    },
    nextSteps() {
      return "bun run build:admin && cd apps/worker && bunx wrangler deploy";
    },
  };
}

async function setupCloudflare(backend: CloudflareBackend, ctx: SetupContext): Promise<void> {
  const dir = workerDir(ctx.cwd);
  const tomlPath = join(dir, "wrangler.toml");
  if (!existsSync(tomlPath)) {
    throw new Error(`No ${tomlPath}. Run this from an OpenCMS checkout.`);
  }

  const whoami = wranglerInvocation(ctx.run, ["whoami"], { cwd: dir });
  if (!isLoggedIn(whoami)) {
    progress(ctx, "Cloudflare login...");
    const login = wranglerInvocation(ctx.run, ["login"], { cwd: dir, inherit: true });
    if (login.status !== 0) throw new Error("wrangler login failed.");
  } else {
    ok(ctx, "Cloudflare account ready");
  }

  let toml = readFileSync(tomlPath, "utf8");
  toml = setWorkerName(toml, backend.workerName);
  toml = setDatabaseName(toml, backend.d1Name);

  const currentId = readDatabaseId(toml);
  if (!isPlaceholderDatabaseId(currentId)) {
    ok(ctx, `D1 already configured (${currentId})`);
  } else {
    const listed = wranglerInvocation(ctx.run, ["d1", "list", "--json"], { cwd: dir });
    const found = parseD1List(listed.stdout + listed.stderr).find((d) => d.name === backend.d1Name);
    let id = found?.id;
    if (!id) {
      progress(ctx, `Creating D1 "${backend.d1Name}"...`);
      const created = wranglerInvocation(ctx.run, ["d1", "create", backend.d1Name], { cwd: dir });
      if (created.status !== 0) {
        throw new Error(`wrangler d1 create failed: ${(created.stderr || created.stdout).trim()}`);
      }
      id = parseDatabaseId(created.stdout + created.stderr);
    }
    if (!id) throw new Error("Could not read D1 database_id from wrangler output.");
    toml = setDatabaseId(toml, id);
    ok(ctx, `D1 "${backend.d1Name}" → ${id}`);
  }

  if (backend.customDomain) {
    toml = upsertCustomDomain(toml, backend.customDomain);
    toml = upsertVars(toml, { BETTER_AUTH_URL: `https://${backend.customDomain}` });
    ok(ctx, `Custom domain ${backend.customDomain}`);
  }

  writeFile(tomlPath, toml);

  const devVarsPath = join(dir, ".dev.vars");
  const authSecret = envAt(devVarsPath).BETTER_AUTH_SECRET || ctx.generateSecret();
  putEnv(
    devVarsPath,
    { BETTER_AUTH_SECRET: authSecret },
    "# Local wrangler dev. Generated by `opencms setup`. Never commit.",
  );
  const put = wranglerInvocation(ctx.run, ["secret", "put", "BETTER_AUTH_SECRET"], {
    cwd: dir,
    input: `${authSecret}\n`,
  });
  if (put.status !== 0) {
    note(
      ctx,
      `Could not put BETTER_AUTH_SECRET remotely (${(put.stderr || put.stdout).trim() || "wrangler failed"}). .dev.vars is set for local dev; run \`wrangler secret put BETTER_AUTH_SECRET\` before deploy.`,
    );
  } else {
    ok(ctx, "BETTER_AUTH_SECRET stored");
  }

  ctx.store = wranglerStore(dir, ctx.run);
}

async function testCloudflare(backend: CloudflareBackend, ctx: SetupContext): Promise<void> {
  const dir = workerDir(ctx.cwd);
  const tomlPath = join(dir, "wrangler.toml");
  if (!existsSync(tomlPath)) {
    throw new Error(`No ${tomlPath}. Run this from an OpenCMS checkout.`);
  }
  const toml = readFileSync(tomlPath, "utf8");
  const id = readDatabaseId(toml);
  if (isPlaceholderDatabaseId(id)) {
    throw new Error("D1 database_id is still the placeholder. Re-run setup.");
  }
  ctx.store = ctx.store ?? wranglerStore(dir, ctx.run);
  if (!envAt(join(dir, ".dev.vars")).BETTER_AUTH_SECRET) {
    throw new Error("BETTER_AUTH_SECRET missing from apps/worker/.dev.vars");
  }
  progress(ctx, `Testing D1 "${backend.d1Name}"...`);
  const ping = wranglerInvocation(
    ctx.run,
    ["d1", "execute", backend.d1Name, "--remote", "--json", "--command", "SELECT 1"],
    { cwd: dir },
  );
  if (ping.status !== 0) {
    throw new Error(
      `D1 "${backend.d1Name}" did not respond: ${(ping.stderr || ping.stdout).trim() || "wrangler failed"}`,
    );
  }
  ok(ctx, `D1 "${backend.d1Name}" reachable`);
}
