/**
 * Turns the wizard's choices into a working project folder: clones the
 * repository, records the choices in opencms.config.ts, and materializes
 * them into the profile's real runtime config (.env for Bun + SQLite,
 * wrangler.toml for Cloudflare). The pure render/patch helpers are exported
 * separately so they are unit-testable without touching git or the disk.
 */
import { spawnSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  BACKEND_FACTORY,
  CACHE_FACTORY,
  FRONTEND_FACTORY,
  STORAGE_FACTORY,
  type CacheConfig,
  type CloudflareBackend,
  type FrontendConfig,
  type InitConfig,
  type SelfHostedBackend,
  type StorageConfig,
} from "./config.ts";
import type { IO } from "./io.ts";
import { palette } from "./io.ts";

export const REPO_URL = "https://github.com/opencmsdev/opencms.git";

/** Folder name derived from the project name: lowercase, dashes, safe. */
export function projectDirName(projectName: string): string {
  const slug = projectName
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  return slug === "" ? "opencms-site" : slug;
}

function jsLiteral(value: unknown): string {
  if (typeof value === "string") return JSON.stringify(value);
  if (typeof value === "number" || typeof value === "boolean") return String(value);
  if (Array.isArray(value)) return `[${value.map(jsLiteral).join(", ")}]`;
  throw new Error(`opencms: cannot render ${typeof value} in opencms.config.ts`);
}

/** `name({ a: 1, b: "x" })`, or `name()` when there is nothing to pass. */
function renderCall(name: string, options: Record<string, unknown>): string {
  const entries = Object.entries(options).filter(([, value]) => value !== undefined);
  if (entries.length === 0) return `${name}()`;
  const body = entries.map(([key, value]) => `    ${key}: ${jsLiteral(value)},`).join("\n");
  return `${name}({\n${body}\n  })`;
}

function optionsOf(obj: object): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(obj)) {
    if (key === "kind" || key === "host") continue;
    if (typeof value === "function") continue;
    out[key] = value;
  }
  return out;
}

function renderBackend(backend: InitConfig["backend"]): string {
  return renderCall(BACKEND_FACTORY[backend.kind], optionsOf(backend));
}

function renderFrontend(frontend: FrontendConfig): string {
  const name = FRONTEND_FACTORY[frontend.host];
  if (frontend.host === "same-origin") return `${name}()`;
  return renderCall(name, optionsOf(frontend));
}

function renderCache(cache: CacheConfig): string {
  return renderCall(CACHE_FACTORY[cache.kind], optionsOf(cache));
}

function renderStorage(storage: StorageConfig): string {
  return renderCall(STORAGE_FACTORY[storage.kind], optionsOf(storage));
}

function usedFactories(config: InitConfig): string[] {
  const names: string[] = [BACKEND_FACTORY[config.backend.kind]];
  if (config.frontend) names.push(FRONTEND_FACTORY[config.frontend.host]);
  if (config.cache) names.push(CACHE_FACTORY[config.cache.kind]);
  if (config.storage) names.push(STORAGE_FACTORY[config.storage.kind]);
  return names;
}

/** The choices as a typed, editable file at the root of the clone. */
export function renderConfigTs(config: InitConfig): string {
  const factories = usedFactories(config);
  const lines = [
    `  projectName: ${jsLiteral(config.projectName)},`,
    `  adminEmail: ${jsLiteral(config.adminEmail)},`,
    `  adminName: ${jsLiteral(config.adminName)},`,
    `  backend: ${renderBackend(config.backend)},`,
  ];
  if (config.frontend) lines.push(`  frontend: ${renderFrontend(config.frontend)},`);
  if (config.cache) lines.push(`  cache: ${renderCache(config.cache)},`);
  if (config.storage) lines.push(`  storage: ${renderStorage(config.storage)},`);

  return [
    "/**",
    " * Generated by `opencms init`: the choices this project was set up with.",
    " * Run `opencms setup` to create the resources those integrations need.",
    " * Edit this file and re-run setup to change the intended stack.",
    " */",
    `import { defineConfig, ${factories.join(", ")} } from "./packages/cli/src/config.ts";`,
    "",
    "export default defineConfig({",
    ...lines,
    "});",
    "",
  ].join("\n");
}

/** Local runtime config for the Bun + SQLite profile; Bun auto-loads it. */
export function renderEnvFile(backend: SelfHostedBackend, secret: string): string {
  const isLocal = /^https?:\/\/(localhost|127\.0\.0\.1)([:/]|$)/.test(backend.publicUrl);
  const lines = [
    "# Generated by `opencms init`. Runtime config for the Bun + SQLite profile.",
    "# Bun loads this automatically for `bun run dev`. Never commit this file.",
    `OPENCMS_DB=${backend.dbPath}`,
    `OPENCMS_PORT=${backend.port}`,
    `BETTER_AUTH_SECRET=${secret}`,
  ];
  if (!isLocal) lines.push(`BETTER_AUTH_URL=${backend.publicUrl}`);
  return lines.join("\n") + "\n";
}

/** Applies worker name, D1 database name and canonical URL to wrangler.toml. */
export function patchWranglerToml(source: string, backend: CloudflareBackend): string {
  let out = source
    .replace(/^name = ".*"$/m, `name = "${backend.workerName}"`)
    .replace(/^database_name = ".*"$/m, `database_name = "${backend.d1Name}"`);
  if (backend.customDomain) {
    out += `\n[vars]\nBETTER_AUTH_URL = "https://${backend.customDomain}"\n`;
  }
  return out;
}

export function generateSecret(): string {
  return randomBytes(32).toString("base64");
}

export interface ScaffoldResult {
  ok: boolean;
  error?: string;
}

/** Clones the repo into `dir` and writes the config files. Never throws. */
export function scaffold(config: InitConfig, dir: string, io: IO): ScaffoldResult {
  const c = palette(io.colorEnabled);
  try {
    if (existsSync(dir)) return { ok: false, error: `./${dir} already exists` };

    io.write(`\n${c.dim(`Cloning ${REPO_URL} into ./${dir} ...`)}\n`);
    const clone = spawnSync("git", ["clone", "--depth", "1", REPO_URL, dir], {
      stdio: ["ignore", "pipe", "pipe"],
      encoding: "utf8",
    });
    if (clone.error) return { ok: false, error: `git is not available (${clone.error.message})` };
    if (clone.status !== 0) {
      const stderr = (clone.stderr ?? "").trim().split("\n").pop() ?? "git clone failed";
      return { ok: false, error: stderr };
    }
    io.write(`${c.green("✔")} Cloned\n`);

    writeFileSync(join(dir, "opencms.config.ts"), renderConfigTs(config));
    io.write(`${c.green("✔")} Wrote opencms.config.ts\n`);

    if (config.backend.kind === "bun-sqlite") {
      writeFileSync(join(dir, ".env"), renderEnvFile(config.backend, generateSecret()));
      io.write(`${c.green("✔")} Wrote .env with a generated BETTER_AUTH_SECRET\n`);
    } else {
      const tomlPath = join(dir, "apps", "worker", "wrangler.toml");
      writeFileSync(tomlPath, patchWranglerToml(readFileSync(tomlPath, "utf8"), config.backend));
      io.write(`${c.green("✔")} Configured apps/worker/wrangler.toml\n`);
    }
    return { ok: true };
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : String(err) };
  }
}
