/**
 * Turns the wizard's choices into a working project folder: clones the
 * repository, records the choices in opencms.config.ts, and materializes
 * them into the profile's real runtime config (.env for Bun + SQLite,
 * wrangler.toml for Cloudflare). The pure render/patch helpers are exported
 * separately so they are unit-testable without touching git or the disk.
 */
import { spawnSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { CloudflareBackend, InitConfig, SelfHostedBackend } from "./config.ts";
import type { IO } from "./io.ts";
import { palette } from "./io.ts";

export const REPO_URL = "https://github.com/opencmsdev/opencms.git";

/** Folder name derived from the project name: lowercase, dashes, safe. */
export function projectDirName(projectName: string): string {
  const slug = projectName
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  return slug === "" ? "opencms-site" : slug;
}

/** The choices as a typed, editable file at the root of the clone. */
export function renderConfigTs(config: InitConfig): string {
  const body = JSON.stringify(config, null, 2).replace(/"([A-Za-z_][A-Za-z0-9_]*)":/g, "$1:");
  return [
    "/**",
    " * Generated by `opencms init`: the choices this project was set up with.",
    " * The setup prompt in opencms-agent-prompt.md follows this file; edit it",
    " * (and re-run your agent) to change the intended setup.",
    " */",
    'import type { InitConfig } from "./packages/cli/src/config.ts";',
    "",
    `const config: InitConfig = ${body};`,
    "",
    "export default config;",
    "",
  ].join("\n");
}

/** Local runtime config for the Bun + SQLite profile; Bun auto-loads it. */
export function renderEnvFile(backend: SelfHostedBackend, secret: string): string {
  const isLocal = /^https?:\/\/(localhost|127\.0\.0\.1)([:/]|$)/.test(backend.publicUrl);
  const lines = [
    "# Generated by `opencms init`. Runtime config for the Bun + SQLite profile.",
    "# Bun loads this automatically for `bun run dev`. Never commit this file.",
    `OPENCMS_DB=${backend.dbPath}`,
    `OPENCMS_PORT=${backend.port}`,
    `BETTER_AUTH_SECRET=${secret}`,
  ];
  if (!isLocal) lines.push(`BETTER_AUTH_URL=${backend.publicUrl}`);
  return lines.join("\n") + "\n";
}

/** Applies worker name, D1 database name and canonical URL to wrangler.toml. */
export function patchWranglerToml(source: string, backend: CloudflareBackend): string {
  let out = source
    .replace(/^name = ".*"$/m, `name = "${backend.workerName}"`)
    .replace(/^database_name = ".*"$/m, `database_name = "${backend.d1Name}"`);
  if (backend.customDomain) {
    out += `\n[vars]\nBETTER_AUTH_URL = "https://${backend.customDomain}"\n`;
  }
  return out;
}

export function generateSecret(): string {
  return randomBytes(32).toString("base64");
}

export interface ScaffoldResult {
  ok: boolean;
  error?: string;
}

/** Clones the repo into `dir` and writes the config files. Never throws. */
export function scaffold(config: InitConfig, dir: string, io: IO): ScaffoldResult {
  const c = palette(io.colorEnabled);
  try {
    if (existsSync(dir)) return { ok: false, error: `./${dir} already exists` };

    io.write(`\n${c.dim(`Cloning ${REPO_URL} into ./${dir} ...`)}\n`);
    const clone = spawnSync("git", ["clone", "--depth", "1", REPO_URL, dir], {
      stdio: ["ignore", "pipe", "pipe"],
      encoding: "utf8",
    });
    if (clone.error) return { ok: false, error: `git is not available (${clone.error.message})` };
    if (clone.status !== 0) {
      const stderr = (clone.stderr ?? "").trim().split("\n").pop() ?? "git clone failed";
      return { ok: false, error: stderr };
    }
    io.write(`${c.green("✔")} Cloned\n`);

    writeFileSync(join(dir, "opencms.config.ts"), renderConfigTs(config));
    io.write(`${c.green("✔")} Wrote opencms.config.ts\n`);

    if (config.backend.kind === "bun-sqlite") {
      writeFileSync(join(dir, ".env"), renderEnvFile(config.backend, generateSecret()));
      io.write(`${c.green("✔")} Wrote .env with a generated BETTER_AUTH_SECRET\n`);
    } else {
      const tomlPath = join(dir, "apps", "worker", "wrangler.toml");
      writeFileSync(tomlPath, patchWranglerToml(readFileSync(tomlPath, "utf8"), config.backend));
      io.write(`${c.green("✔")} Configured apps/worker/wrangler.toml\n`);
    }
    return { ok: true };
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : String(err) };
  }
}
