/**
 * Context passed to every integration's `setup`. Backend integrations install
 * `store` so storage integrations can persist keys without knowing whether
 * the project is Bun + `.env` or Workers + wrangler secrets.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { parseEnv, upsertEnv } from "./env-file.ts";
import type { IO } from "./io.ts";
import { palette } from "./io.ts";
import { text } from "./prompts.ts";
import { upsertVars } from "./toml.ts";
import { wranglerInvocation, type Run } from "./wrangler.ts";

export interface SetupContext {
  cwd: string;
  io: IO;
  run: Run;
  yes?: boolean;
  generateSecret: () => string;
  /** Installed by the backend integration during its setup. */
  store?: SecretStore;
  /** Injected in tests so S3/R2 probes never hit the network. */
  fetch?: (input: Request | string | URL, init?: RequestInit) => Promise<Response>;
}

export interface SecretStore {
  read(): Record<string, string>;
  put(values: Record<string, string | undefined>, secrets?: string[]): void;
}

export interface Integration {
  plan(): string[];
  setup(ctx: SetupContext): void | Promise<void>;
  /** Prove the integration actually works: ping D1, ListObjects on R2, etc. */
  test(ctx: SetupContext): void | Promise<void>;
  nextSteps?(): string;
}

export function isIntegration(value: unknown): value is Integration {
  return (
    typeof value === "object" &&
    value !== null &&
    typeof (value as Integration).setup === "function" &&
    typeof (value as Integration).plan === "function" &&
    typeof (value as Integration).test === "function"
  );
}

export function workerDir(cwd: string): string {
  return join(cwd, "apps", "worker");
}

export function writeFile(path: string, contents: string): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, contents);
}

export function readOptional(path: string): string {
  return existsSync(path) ? readFileSync(path, "utf8") : "";
}

export function envAt(path: string): Record<string, string> {
  return parseEnv(readOptional(path));
}

export function putEnv(
  path: string,
  updates: Record<string, string | undefined>,
  header?: string,
): void {
  const current = readOptional(path);
  const base = current === "" && header ? `${header}\n` : current;
  writeFile(path, upsertEnv(base, updates));
}

export async function askSecret(
  io: IO,
  title: string,
  existing: string | undefined,
  yes: boolean | undefined,
): Promise<string | undefined> {
  if (existing) return existing;
  if (yes) return undefined;
  return text(io, title, { required: true });
}

export function envStore(path: string): SecretStore {
  return {
    read: () => envAt(path),
    put(values) {
      putEnv(path, values);
    },
  };
}

export function wranglerStore(dir: string, run: Run): SecretStore {
  const devVars = join(dir, ".dev.vars");
  const tomlPath = join(dir, "wrangler.toml");
  return {
    read: () => envAt(devVars),
    put(values, secrets = []) {
      const secretSet = new Set(secrets);
      const publicVars: Record<string, string> = {};
      const all: Record<string, string | undefined> = { ...values };
      putEnv(
        devVars,
        all,
        "# Local wrangler dev. Generated by `opencms setup`. Never commit.",
      );
      for (const [key, value] of Object.entries(values)) {
        if (value === undefined) continue;
        if (secretSet.has(key)) {
          wranglerInvocation(run, ["secret", "put", key], { cwd: dir, input: `${value}\n` });
        } else {
          publicVars[key] = value;
        }
      }
      if (existsSync(tomlPath) && Object.keys(publicVars).length > 0) {
        writeFile(tomlPath, upsertVars(readFileSync(tomlPath, "utf8"), publicVars));
      }
    },
  };
}

export function ok(ctx: SetupContext, message: string): void {
  ctx.io.write(`${palette(ctx.io.colorEnabled).green("✔")} ${message}\n`);
}

export function note(ctx: SetupContext, message: string): void {
  ctx.io.write(`${palette(ctx.io.colorEnabled).dim("ℹ")} ${message}\n`);
}

export function progress(ctx: SetupContext, message: string): void {
  ctx.io.write(`${palette(ctx.io.colorEnabled).dim("→")} ${message}\n`);
}
